title: Meera’s RLAC Diary 🎀
description: >-
  A collection of my work, thoughts, and experiments from Reading Like a Computer at NYU Abu Dhabi.
github_username: mrh9663-del
minimal_mistakes_skin: air
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
timezone: Asia/Dubai

include:
  - _pages

author:
  name: "Meera Alshamsi"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "just me, reading like a computer and trying to make sense of it 💌"

tag_archive:
  type: liquid
  path: /tags/
